//AUTH
export const STARTAUTHLISTEN = 'STARTAUTHLISTEN';
export const AUTHENTICATED = 'AUTHENTICATED';
export const UNAUTHENTICATED = 'UNAUTHENTICATED';
export const LOGINSUCCESS = 'LOGINSUCCESS';
export const LOGINFAILED = 'LOGINFAILED';
export const SIGNUPSUCCESS = 'SIGNUPSUCCESS';
export const SIGNUPFAILED = 'SIGNUPFAILED';
export const LOGOUTSUCCESS = 'LOGOUTSUCCESS';

//TODOS
export const FETCHTODOSSUCCESS = 'FETCHTODOSSUCCESS';
export const FETCHTODOSFAILED = 'FETCHTODOSFAILED';
export const WRITETODOSSUCCESS = 'WRITETODOSSUCCESS';
export const WRITETODOSFAILED = 'WRITETODOSFAILED';
export const DELETETODOSUCCESS = 'DELETETODOSUCCESS';
export const DELETETODOFAILED = 'DELETETODOFAILED';
export const PATCHTODOSUCCESS = 'PATCHTODOSUCCESS';
export const PATCHTODOFAILED = 'PATCHTODOFAILED';