export const AUTHENTICATED = 'AUTHENTICATED';
export const UNAUTHENTICATED = 'UNAUTHENTICATED';
export const LOGINSUCCESS = 'LOGINSUCCESS';
export const LOGINFAILED = 'LOGINFAILED';
export const SIGNUPSUCCESS = 'SIGNUPSUCCESS';
export const SIGNUPFAILED = 'SIGNUPFAILED';
export const LOGOUTSUCCESS = 'LOGOUTSUCCESS';